# Generated by Django 3.1.7 on 2021-04-05 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LenteCup2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('first_name', models.CharField(max_length=40, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Speler',
                'verbose_name_plural': 'Spelers',
                'ordering': ('rank', 'first_name', 'last_name'),
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='GekozenSpelers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gekozen', to='LenteCup2.speler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gekozen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'speler'),
                'unique_together': {('user', 'speler')},
            },
        ),
    ]
