# Generated by Django 3.1.7 on 2021-04-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0003_auto_20210405_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speler',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
