# Generated by Django 3.1.7 on 2021-04-06 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LenteCup2', '0006_gekozenspelers_eindplaats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gekozenspelers',
            name='eindplaats',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='gekozenspelers',
            name='speler',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gekozen', to='LenteCup2.speler'),
        ),
        migrations.AlterField(
            model_name='gekozenspelers',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gekozen', to=settings.AUTH_USER_MODEL),
        ),
    ]
