# Generated by Django 3.1.7 on 2021-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0007_auto_20210406_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekozenspelers',
            name='punten',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
