# Generated by Django 3.1.7 on 2021-04-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0008_gekozenspelers_punten'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speler',
            options={'ordering': ('position', 'first_name', 'last_name'), 'verbose_name': 'Speler', 'verbose_name_plural': 'Spelers'},
        ),
    ]
