# Generated by Django 3.1.7 on 2021-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0009_auto_20210407_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourstarttime', models.DateTimeField(default='2021, 4, 8, 12, 1, 59, 342380')),
            ],
        ),
    ]
