# Generated by Django 3.1.7 on 2021-04-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0010_gamesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='tourstarttime',
            field=models.DateTimeField(),
        ),
    ]
