# Generated by Django 3.1.7 on 2021-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0011_auto_20210407_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesettings',
            name='tourstarttime',
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='gamesettings',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
