# Generated by Django 3.1.7 on 2021-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0012_auto_20210408_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='gamesettingsvalue',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
