# Generated by Django 3.1.7 on 2021-04-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0013_gamesettings_gamesettingsvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ('-weeknummer', 'week'), 'verbose_name': 'Week', 'verbose_name_plural': 'Weken'},
        ),
    ]
