# Generated by Django 3.1.7 on 2021-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LenteCup2', '0014_auto_20210409_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='speler',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
