# Generated by Django 3.1.7 on 2021-05-06 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=30)),
                ('directory', models.CharField(max_length=30)),
                ('openforsubscribing', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('apparea', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AppAuthorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isauthorised', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appauthorisation', to='common.apps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appauthorisation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
