# Generated by Django 3.1.7 on 2022-10-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wk2022', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('NL', 'Netherlands'), ('DE', 'Germany'), ('AZ', 'Azerbeijan'), ('IR', 'Ireland'), ('ES', 'Spain'), ('RO', 'Roumania'), ('IT', 'Italy'), ('DK', 'Denmark'), ('RU', 'Russia'), ('SC', 'Scotland'), ('UK', 'England'), ('HU', 'Hungary'), ('QA', 'Qatar')], max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=4, null=True, verbose_name='Group'),
        ),
    ]
