# Generated by Django 3.1.7 on 2022-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wk2022', '0002_auto_20221005_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1, verbose_name='Group'),
        ),
    ]
