# Generated by Django 3.1.7 on 2022-10-05 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wk2022', '0003_auto_20221005_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='leaguebalance',
            field=models.PositiveIntegerField(default=64000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='League Balance'),
        ),
    ]
