# Generated by Django 3.1.7 on 2021-07-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0002_auto_20210721_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfbaanprofiel',
            name='sr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3),
        ),
    ]
