# Generated by Django 3.1.7 on 2021-07-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0003_auto_20210722_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfprofiel',
            name='opmerking',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
