# Generated by Django 3.1.7 on 2021-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0004_auto_20210722_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfprofiel',
            name='ehcp',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
