# Generated by Django 3.1.7 on 2021-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0006_auto_20210723_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfprofiel',
            name='lohcp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
