# Generated by Django 3.1.7 on 2021-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0007_auto_20210723_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfprofiel',
            name='preluukopen',
            field=models.BooleanField(default=False),
        ),
    ]
