# Generated by Django 3.1.7 on 2021-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0008_golfprofiel_preluukopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfprofiel',
            name='verradergame',
            field=models.BooleanField(default=True),
        ),
    ]
