# Generated by Django 3.2.6 on 2021-09-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0010_auto_20210815_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holes',
            new_name='Hole',
        ),
        migrations.RenameField(
            model_name='baanprofiel',
            old_name='plaats',
            new_name='adres',
        ),
        migrations.AddField(
            model_name='baanprofiel',
            name='telefoon',
            field=models.CharField(default='Onbekend', max_length=60),
        ),
    ]
