# Generated by Django 3.1.7 on 2021-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0010_auto_20210815_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfprofiel',
            name='totalscore',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
