# Generated by Django 3.2.6 on 2021-09-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0011_auto_20210906_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=60)),
                ('dag', models.CharField(max_length=60)),
                ('starttijd', models.CharField(max_length=60)),
                ('golfbaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='luukopen21.golfbaanprofiel')),
                ('spelers', models.ManyToManyField(to='luukopen21.GolfProfiel')),
            ],
        ),
    ]
