# Generated by Django 3.2.6 on 2021-09-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0011_golfprofiel_totalscore'),
        ('luukopen21', '0012_flight'),
    ]

    operations = [
    ]
