# Generated by Django 3.1.7 on 2021-09-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0013_merge_0011_golfprofiel_totalscore_0012_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40)),
            ],
        ),
    ]
