# Generated by Django 3.1.7 on 2021-09-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0014_scum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfprofiel',
            name='totalscore',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
