# Generated by Django 3.1.7 on 2021-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luukopen21', '0015_auto_20210910_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfprofiel',
            name='totalscore',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
