# Generated by Django 3.1.7 on 2021-05-09 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Name')),
                ('shortname', models.CharField(default='NUL', max_length=3, verbose_name='Ctry')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Order')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='Group')),
                ('openforbid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('group', 'order'),
            },
        ),
        migrations.CreateModel(
            name='GamePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamephase', models.CharField(max_length=40, verbose_name='Game Phase')),
                ('allowbidding', models.BooleanField(default=False)),
                ('allowauction', models.BooleanField(default=False)),
                ('allowlineup', models.BooleanField(default=False)),
                ('allowfiring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaguename', models.CharField(max_length=30, unique=True, verbose_name='League Name')),
                ('maxparticipants', models.PositiveSmallIntegerField(verbose_name='Max Teams')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private League')),
                ('leaguebalance', models.PositiveIntegerField(default=48000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='League Balance')),
                ('leaguefee', models.DecimalField(decimal_places=2, default=10.0, max_digits=4)),
                ('secretnumber', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)], verbose_name='Secret key')),
                ('gamephase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaguephase', to='euro2020.gamephase')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Name')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('country', models.CharField(choices=[('NL', 'Netherlands'), ('DE', 'Germany'), ('AZ', 'Azerbeijan'), ('IR', 'Ireland'), ('ES', 'Spain'), ('RO', 'Roumania'), ('IT', 'Italy'), ('DK', 'Denmark'), ('RU', 'Russia'), ('SC', 'Scotland'), ('UK', 'England'), ('HU', 'Hungary')], max_length=2, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('betcoins', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('bidbudget', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('maxbidgke', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('maxbiddef', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('maxbidmid', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('maxbidatt', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=4, null=True, verbose_name='Group')),
                ('paid', models.BooleanField(default=False)),
                ('eliminated', models.BooleanField(default=False)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='euro2020.league')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('M', 'Midfielder'), ('A', 'Attacker')], max_length=1)),
                ('number', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Number')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='euro2020.country')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ('country', 'position', 'number'),
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('G1', 'Group Stage Day 1'), ('G2', 'Group Stage Day 2'), ('G3', 'Group Stage Day 3'), ('Q6', 'Round of 16'), ('Q8', 'Quarter Final'), ('Q4', 'Semi Final'), ('Q2', 'Final')], max_length=2, verbose_name='Stage')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('has_started', models.BooleanField(default=False, verbose_name='Started')),
                ('has_ended', models.BooleanField(default=False, verbose_name='Ended')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='euro2020.country')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='euro2020.country')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='euro2020.location')),
                ('players', models.ManyToManyField(related_name='matches', to='euro2020.Player')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GO', 'Goal'), ('PE', 'Penalty'), ('OG', 'OwnGoal')], default='GO', max_length=2, verbose_name='Type of Goal')),
                ('minute', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Minute')),
                ('phase', models.CharField(choices=[('1R', 'Regular Time'), ('2E', 'Extra Time'), ('3P', 'Penalty Shoot out')], default='1R', max_length=2, verbose_name='Phase')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='euro2020.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='euro2020.player')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['phase', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerbid', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('assigned', models.BooleanField(null=True)),
                ('bidcomment', models.CharField(default='Bid Created', max_length=200, null=True, verbose_name='Bid Comment')),
                ('gamephase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='euro2020.gamephase')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='euro2020.player')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='euro2020.team')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['team'],
            },
        ),
    ]
