# Generated by Django 3.1.7 on 2021-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0003_bids_previousteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draw',
            field=models.BooleanField(default=False, verbose_name='Loting plaatsgevonden'),
        ),
    ]
