# Generated by Django 3.1.7 on 2021-05-20 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0006_boekhoudingleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boekhouding',
            name='aantalbetcoins',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(48000)]),
        ),
        migrations.AlterField(
            model_name='boekhoudingleague',
            name='aantalbetcoins',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(48000)]),
        ),
    ]
