# Generated by Django 3.1.7 on 2021-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0007_auto_20210520_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opstelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opgesteldespeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opstelling', to='euro2020.player')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opstelling', to='euro2020.gamephase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opstelling', to='euro2020.team')),
            ],
        ),
    ]
