# Generated by Django 3.1.7 on 2021-05-22 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0009_auto_20210522_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boekhoudingleague',
            name='aantalbetcoins',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-48000), django.core.validators.MaxValueValidator(48000)]),
        ),
    ]
