# Generated by Django 3.1.7 on 2021-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0011_auto_20210522_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('G1', 'Groepsronde 1'), ('G2', 'Groepsronde 2'), ('G3', 'Groepsronde 3'), ('Q6', 'Achtste Finales'), ('Q8', 'Kwart Finales'), ('Q4', 'Halve Finales'), ('Q2', 'Finale')], max_length=2, verbose_name='Stage'),
        ),
    ]
