# Generated by Django 3.1.7 on 2021-06-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0013_opstellinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactiek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactiek', models.CharField(choices=[('Normaal', 'Normaal'), ('Aanvallend', 'geen minpunten, 25% pluspunten')], max_length=20)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactiek', to='euro2020.gamephase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactiek', to='euro2020.team')),
            ],
        ),
    ]
