# Generated by Django 3.1.7 on 2021-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0014_tactiek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('G1', 'GroepsRonde 1'), ('G2', 'GroepsRonde 2'), ('G3', 'GroepsRonde 3'), ('Q6', 'Achtste Finales'), ('Q8', 'Kwart Finales'), ('Q4', 'Halve Finales'), ('Q2', 'Finale')], max_length=2, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='tactiek',
            name='tactiek',
            field=models.CharField(choices=[('Normaal', 'Normaal'), ('Aanvallend', 'Aanvallend')], max_length=20),
        ),
    ]
