# Generated by Django 3.1.7 on 2021-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0015_auto_20210605_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('G1', 'GroepsRonde 1'), ('G2', 'GroepsRonde 2'), ('G3', 'GroepsRonde 3'), ('Q6', 'Achtste Finales'), ('Q8', 'Kwart Finales'), ('Q4', 'Halve Finales'), ('Q2', 'Grande Finale')], max_length=2, verbose_name='Stage'),
        ),
    ]
