# Generated by Django 3.1.7 on 2021-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0017_virtualmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmatch',
            name='awayscore',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='virtualmatch',
            name='decimalawayscore',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='virtualmatch',
            name='decimalhomescore',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='virtualmatch',
            name='homescore',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
