# Generated by Django 3.1.7 on 2021-06-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0018_auto_20210606_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmatch',
            name='minusdecimalawayscore',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='virtualmatch',
            name='minusdecimalhomescore',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
