# Generated by Django 3.1.7 on 2021-06-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0019_auto_20210606_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='opstelling',
            name='goalscore',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='opstelling',
            name='minscore',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='opstelling',
            name='nulscore',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='opstelling',
            name='plusscore',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
