# Generated by Django 3.1.7 on 2021-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0020_auto_20210606_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='premiebasis',
            field=models.IntegerField(default=0),
        ),
    ]
