# Generated by Django 3.1.7 on 2021-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0021_league_premiebasis'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmatch',
            name='decimalawaygoalscore',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='virtualmatch',
            name='decimalhomegoalscore',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
