# Generated by Django 3.1.7 on 2021-06-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0022_auto_20210615_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmatch',
            name='awayscore',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='decimalawaygoalscore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='decimalawayscore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='decimalhomegoalscore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='decimalhomescore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='homescore',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='minusdecimalawayscore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='minusdecimalhomescore',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
