# Generated by Django 3.1.7 on 2021-06-20 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0023_auto_20210615_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Order'),
        ),
    ]
