# Generated by Django 3.1.7 on 2021-06-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0025_auto_20210620_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='ontslaan',
            field=models.BooleanField(default=False),
        ),
    ]
