# Generated by Django 3.1.7 on 2021-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0027_auto_20210626_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='opstelling',
            name='verlenging',
            field=models.BooleanField(default=False),
        ),
    ]
