# Generated by Django 3.1.7 on 2021-06-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0028_opstelling_verlenging'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamephase',
            name='kophase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='homewonshootout',
            field=models.BooleanField(default=False),
        ),
    ]
