# Generated by Django 3.1.7 on 2021-06-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0029_auto_20210627_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmatch',
            name='homewonshootout',
            field=models.BooleanField(default=False),
        ),
    ]
