# Generated by Django 3.1.7 on 2021-07-03 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0031_match_readurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='betcoins',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
