# Generated by Django 3.1.7 on 2021-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0032_auto_20210703_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='koreference',
            field=models.CharField(default='', max_length=4),
        ),
    ]
