# Generated by Django 3.1.7 on 2021-07-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0034_virtualmatch_koreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='koreference',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='virtualmatch',
            name='koreference',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
